[package]
name = "weaver-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
petgraph = "0.6.5"
itertools = "0.13.0"
static_assertions = "1.1.0"
glam = "0.27.0"
rayon = "1.5.1"
atomic_refcell = "0.1.13"

weaver-util = { path = "../weaver-util" }
weaver-ecs-macros = { path = "../weaver-ecs-macros" }
weaver-reflect-macros = { path = "../weaver-reflect-macros" }
