[package]
name = "weaver-demo"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_plot = "0.29"

[profile.release]
debug = true
opt-level = 3
