[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "weaver-proc-macro",
    "weaver-core",
    "weaver-ecs",
    "weaver-game",
    "weaver-editor",
]
exclude = ["weaver-bench"]

[features]
default = []

[lib]
name = "weaver"
path = "src/lib.rs"

[dependencies]
glam = "0.24"
anyhow = "1.0"
parking_lot = "0.12"
winit = "0.29"
egui = "0.25"
weaver-core = { path = "weaver-core" }
weaver-ecs = { path = "weaver-ecs" }
weaver-proc-macro = { path = "weaver-proc-macro" }


[profile.release]
debug = true
opt-level = 3
# codegen-units = 1
# lto = "thin"
