[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
thiserror = "1.0.49"
raqote = "0.8.3"
pixels = "0.13.0"
winit = "0.28.7"
winit_input_helper = "0.14.1"
glam = "0.24.2"
