[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["weaver-proc-macro", "weaver-core", "weaver-ecs", "weaver-game"]
exclude = ["weaver-bench"]

[features]
default = []

[lib]
name = "weaver"
path = "src/lib.rs"

[dependencies]
weaver-core = { path = "weaver-core" }
weaver-ecs = { path = "weaver-ecs" }


[profile.release]
debug = true
opt-level = 2
# codegen-units = 1
# lto = "thin"
