[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["weaver-proc-macro"]

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
thiserror = "1.0.49"
winit = "0.28"
winit_input_helper = "0.14"
glam = { version = "0.24.2", features = ["serde", "bytemuck"] }
rustc-hash = "1.1.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
tobj = "4.0.0"
egui = "0.24"
egui-wgpu = "0.24"
egui-winit = { version = "0.24", default-features = false, features = [
    "links",
] }
wgpu = "0.18"
rand = "0.8.5"
futures = "0.3.29"
itertools = "0.12.0"
gltf = "1.4.0"
pollster = "0.3.0"
weaver-proc-macro = { path = "weaver-proc-macro" }
static_assertions = "1.1.0"
image = "0.24.7"
petgraph = "0.6.4"
egui_plot = "0.24.2"
futures-channel = "0.3.30"
bit-set = "0.5.3"
rapier3d = "0.17.2"
nalgebra = { version = "0.32.3", features = ["convert-glam024"] }
clap = { version = "4.4.13", features = ["derive"] }

[profile.release]
debug = true
opt-level = 2
# codegen-units = 1
# lto = "thin"
