[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/weaver-proc-macro",
    "crates/weaver-core",
    "crates/weaver-editor",
]

[features]
default = []

[lib]
name = "weaver"
path = "src/lib.rs"

[dependencies]
glam = "0.24"
anyhow = "1.0"
parking_lot = { version = "0.12", features = ["arc_lock"] }
winit = "0.29"
egui = "0.25"
weaver-core = { path = "crates/weaver-core" }
weaver-proc-macro = { path = "crates/weaver-proc-macro" }

[dev-dependencies]
criterion = "0.5"

[profile.release]
debug = true
opt-level = 3
# codegen-units = 1
# lto = "thin"
