[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
thiserror = "1.0.49"
pixels = { git = "https://github.com/parasyte/pixels.git" }
winit = "0.28"
winit_input_helper = "0.14"
glam = { version = "0.24.2", features = ["serde"] }
typed-arena = "2.0.2"
rustc-hash = "1.1.0"
bytemuck = "1.14.0"
tobj = "4.0.0"
egui = "0.23"
egui-wgpu = "0.23"
egui-winit = { version = "0.23", default-features = false, features = [
    "links",
] }
wgpu = "0.17"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
petgraph = "0.6.4"
tokio = { version = "1.35.0", features = ["full"] }
futures = "0.3.29"
itertools = "0.12.0"
