[package]
name = "weaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/weaver-proc-macro",
    "crates/weaver-app",
    "crates/weaver-editor",
    "crates/weaver-util",
    "crates/weaver-ecs",
    "crates/weaver-renderer",
    "crates/weaver-winit",
]

[features]
default = []

[lib]
name = "weaver"
path = "src/lib.rs"

[dependencies]
glam = "0.27.0"
anyhow = "1.0"
parking_lot = { version = "0.12", features = ["arc_lock"] }
winit = "0.30.0"

weaver-app = { path = "crates/weaver-app" }
weaver-proc-macro = { path = "crates/weaver-proc-macro" }
weaver-util = { path = "crates/weaver-util" }
weaver-ecs = { path = "crates/weaver-ecs" }
weaver-renderer = { path = "crates/weaver-renderer" }
weaver-winit = { path = "crates/weaver-winit" }

[dev-dependencies]
criterion = "0.5"

[profile.release]
debug = true
opt-level = 3
# codegen-units = 1
# lto = "thin"
