[package]
name = "weaver-winit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
winit = "0.29.15"

weaver-app = { path = "../weaver-app" }
weaver-ecs = { path = "../weaver-ecs" }
