[package]
name = "weaver-asset"
version = "0.1.0"
edition = "2021"

[dependencies]
tobj = "4.0.2"

weaver-util = { path = "../weaver-util" }
weaver-ecs = { path = "../weaver-ecs" }
weaver-core = { path = "../weaver-core" }
weaver-app = { path = "../weaver-app" }
weaver-renderer = { path = "../weaver-renderer" }
