[package]
name = "weaver-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
parking_lot = "0.12"
rustc-hash = "1.1"
petgraph = "0.6"
rayon = "1.8"
crossbeam-channel = "0.5"
weaver-proc-macro = { path = "../weaver-proc-macro" }
