[package]
name = "weaver-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1"
weaver-proc-macro = { path = "../weaver-proc-macro" }
itertools = "0.12"
thiserror = "1.0.52"
rayon = "1.8"
