[package]
name = "weaver-util"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = { version = "0.12.1", features = ["arc_lock", "send_guard"] }
lock_api = "0.4.0"
anyhow = "1.0.86"
downcast-rs = "1.0.0"
