[package]
name = "weaver-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
naga_oil = "0.14.0"
wgpu = { version = "0.20.0", features = ["naga-ir"] }
glam = { version = "0.27.0", features = ["bytemuck"] }
anyhow = "1.0.40"
bytemuck = { version = "1.16.0", features = ["derive"] }
winit = "0.30.0"
pollster = "0.3.0"
petgraph = "0.6.5"

weaver-app = { path = "../weaver-app" }
weaver-util = { path = "../weaver-util" }
weaver-ecs = { path = "../weaver-ecs" }
weaver-proc-macro = { path = "../weaver-proc-macro" }
weaver-core = { path = "../weaver-core" }
weaver-asset = { path = "../weaver-asset" }
