[package]
name = "weaver-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20.0"
glam = { version = "0.27.0", features = ["bytemuck"] }
anyhow = "1.0.40"
bytemuck = { version = "1.16.0", features = ["derive"] }

weaver-util = { path = "../weaver-util" }
weaver-ecs = { path = "../weaver-ecs" }
weaver-proc-macro = { path = "../weaver-proc-macro" }
