[package]
name = "weaver-reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.27.0"

weaver-util = { path = "../weaver-util" }
weaver-reflect-macros = { path = "../weaver-reflect-macros" }
weaver-ecs = { path = "../weaver-ecs" }
